### ISSUE TITLE
Include this into RLP library?

### ISSUE THREAD

**Issue by holgerd77** [machinomy/types-rlp#1]
Hi Sergey,
this is Holger, I'm a maintainer of EthereumJS project. We just have some issue questions on having TypeScript integrated/supported in the ``rlp`` library: https://github.com/ethereumjs/rlp/issues/24

Are you open for the idea of directly including this in the library? If so would you ideally have some free hour of doing a PR on this and assist a bit on how to integrate/reference this in ``package.json`` (we're all not really TypeScript experts)?

That would be great! 😄

**Comment by ukstv** [comment]
(1) we could move current types-rlp to "@types/rlp" package. (2) Weird scenario is 'rlp' package uses 'types-rlp' as git submodule for types only. (3) Move the definitions to 'rlp' project altogether. That would mean you guys are responsible for maintaining the definitions :P And, that is the best way.

**Comment by ukstv** [comment]
@holgerd77 What is your choice?

**Comment by ukstv** [comment]
Oohs, you guys use safe-buffer, which does not have any definitions :/

Linked: https://github.com/feross/safe-buffer/issues/20

**Comment by holgerd77** [comment]
Yes, I could exclude options (1) or (2), since both include new dependencies in an over-blown way. So if we continue on this, (3) would be the option.

I'm not getting the bigger picture of your ``safe-buffer`` comment. Is this just another issue independent from this issue or has this some inter-dependencies with the issue here?

**Comment by ukstv** [comment]
Type declaration here depends on `buffer` package. `safe-buffer` provides the same API, but is different still. It lacks type declaration.
So, to move declarations to `rlp` we have to create ones for `safe-buffer` first. And, we have options here: (1) depend on a separate package, or (2) have it included in `safe-buffer` repo.

**Comment by vietlq** [comment]
Thanks @holgerd77 & @ukstv for working on this! Hats off to the speed & collaboration spirit! :+1:

**Comment by ukstv** [comment]
Basically, if we hear nothing from Feross, we better go with a declarations package for `safe-buffer`, and merge `types-rlp` declarations to `rlp` package.

**Comment by vietlq** [comment]
Awesome! I tried learning TypeScript over the weekend, but that's not enough to do this kind of work :) Will learn from experts like you.

**Comment by holgerd77** [comment]
@ukstv Ah, I don't want to introduce new dependencies for this. For this TypeScript is still too much on a sidetrack for us and we are generally careful with adding new/too much dependencies.

**Comment by ukstv** [comment]
@holgerd77 See https://github.com/ethereumjs/rlp/pull/25 No new dependencies, as `safe-buffer` includes its own declarations.
